hotfix: Add run_time=1 default value to enable saving reports
Fixed TypeError when clicking save button: insert_fixes() missing 1 required positional argument

The insert_fixes() and save_error_records() functions require run_time parameter,
but save_json_data endpoint was not passing it.

Quick fix:
- Added run_time=1 as default value to insert_fixes() call
- Added run_time=1 as default value to save_error_records() call

This enables the save functionality immediately while maintaining
data integrity (all auto-saved reports will have run_time=1).